config/routes.rb
Rails.application.routes.draw do
  resources :requests
  resources :events
  devise_for :users
  get 'home/index'
  get 'home/about'
  get 'home/calendar'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	validates_presence_of :name, :start_date, :end_date

	validates :start_date,
    Date: { after: Proc.new { Date.today }, message: 'must be after today' },
    on: :create
    validates :start_date,
    Date: { after: Proc.new { Date.today }, message: 'must be after today' },
    on: :update
    validates :end_date,
    Date: { after_or_equal_to: :start_date, message: 'of the holiday cannot be before the start date' },
    on: :create
    validates :end_date,
    Date: { after_or_equal_to: :start_date, message: 'of the holiday cannot be before the start date' },
    on: :update
end

app/models/request.rb
class Request < ApplicationRecord
	validates_presence_of :title, :start_date, :end_date

	validates :end_date,
    Date: { after_or_equal_to: :start_date, message: 'of the holiday cannot be before the start date' },
    on: :create
    validates :end_date,
    Date: { after_or_equal_to: :start_date, message: 'of the holiday cannot be before the start date' },
    on: :update
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :events
         validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

def authorize
  unless current_user.admin == true
    flash[:alert] = "Unauthorized access"
    redirect_to home_calendar_path
    false
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [ :show, :edit, :update, :destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    #@event = Event.new
    @event = current_user.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    #@event = Event.new(event_params)
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    if current_user.admin == false
      @event = current_user.events.find_by(id: params[:id])
      redirect_to root_path, notice: "Unauthorized access" if @event.nil?
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :notes, :start_date, :end_date, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def calendar
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize, only: %i[ create show edit update destroy]

  # GET /requests or /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1 or /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new
  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests or /requests.json
  def create
    @request = Request.new(request_params)

    respond_to do |format|
      if @request.save
        format.html { redirect_to request_url(@request), notice: "Request was successfully created." }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1 or /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to request_url(@request), notice: "Request was successfully updated." }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1 or /requests/1.json
  def destroy
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url, notice: "Request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def request_params
      params.require(:request).permit(:title, :description, :start_date, :end_date)
    end
end

app/controllers/users/devise_controller.rb
# This controller is a solution to the problem of incorrectly displayed alerts and notifications
# Created by Nejdet Kadir Bektaş
# https://medium.com/@nejdetkadir/how-to-use-devise-gem-with-ruby-on-rails-7-33b89f9a9c13

class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>" class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">
  <p>
    <strong>Name:</strong>
    <%= event.name %>
  </p>

  <p>
    <strong>ID:</strong>
    <%= event.user_id %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= event.notes %>
  </p>

  <p>
    <strong>Start date (The first day you will not be present):</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>End date (The first day you will be present):</strong>
    <%= event.end_date %>
  </p>

  <p>
    <strong>Request submited on: </strong>
    <%= event.created_at %>
  </p>

</div>

app/views/events/edit.html.erb
<h1 class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">Edit Holiday Request</h1>

<%= render "form", event: @event %>

<br>

<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
  <%= link_to "Show This Holiday Request", @event %> 
  <%= link_to "Back To Holiday Requests", events_path %>
</div>

app/views/events/index.html.erb
<h1 id="header" style="position:relative" class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">Holiday Requests</h1>
<span class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
  <%= link_to "New Holiday Request", new_event_path %>
</span>
<div id="events" class="wrapper-requests">
  <% @events.each do |event| %>
    <% if event.user == current_user %>
      <hr class="container" />
      <%= render event %>
      <p class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
        <%= link_to "Show This Holiday Request", event %>
      </p>
    <% end %>
  <% end %>

  <% @events.each do |event| %>
    <% if current_user.admin == true %>
      <hr class="container" />
      <%= render event %>
      <p class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
        <%= link_to "Show This Holiday Request", event %>
      </p><br/>
    <% end %>
  <% end %>
</div>
<script> 
$(document).ready(function(){
    $("#header").animate({bottom: '40px'}, 600);
  });
</script>

app/views/events/new.html.erb
<h1 class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">Holiday Request Form</h1>

<%= render "form", event: @event %>

<br>

<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
  <%= link_to "Back To Holiday Requests", events_path %>
</div>

app/views/events/show.html.erb
<%= render @event %>

<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
  <%= link_to "Edit This Holiday Request", edit_event_path(@event) %> 
  <%= link_to "Back To Holiday Requests", events_path %>
  <%= link_to "Show Calendar", home_calendar_path %>
  <%= button_to "Cancel This Request", @event, method: :delete, class:"btn btn-sm-primary mt-4" %>
</div>

app/views/home/_footer.html.erb
<!-- used Bootstrap footer template from: https://mdbootstrap.com/docs/standard/navigation/footer/ -->
<div class="cover-container links-primary">
  <footer class="text-center text-lg-start text-white" style="background-color: #45526e"          >
    <div class="container p-5 pb-0">
      <section class="">
        <div class="row">
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Project Information
            </h6>
            <%= link_to root_path do %>
              <%= image_tag("logo.png", :alt => "logo", :class => "logo-footer float-start mb-3", width: "50", height: "48") %>
            <% end %>
            <p>
              The Holidays Management System is a project developed by <a href="https://www.linkedin.com/in/jarek-polowy/" target="_blank" rel= "noreferrer">Jarek Polowy</a>.
              Navigate to the <%= link_to 'About', home_about_path %> page to learn more. This instance of the application is for demonstration purposes only.
            </p>
          </div>

          <hr class="w-100 clearfix d-md-none" />

          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Navigation
            </h6>
            <p>
              <%= link_to 'Home', root_path %>
            </p>
            <p>
              <%= link_to 'About HMS', home_about_path %>
            </p>
            <p>
              <%= link_to 'Register', new_user_registration_path %>
            </p>
            <p>
              <%= link_to 'Sign In', new_user_session_path %>
            </p>
          </div>

          <hr class="w-100 clearfix d-md-none" />
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Holidays
            </h6>
            <p>
              <%= link_to 'View Calendar', home_calendar_path %>
            </p>
            <p>
              <%= link_to 'Create Holiday Request', events_path %>
            </p>
            <p>
              <%= link_to 'Manage account', edit_user_registration_path %>
            </p>
          </div>

          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> Holidays Management System</p>
            <p><i class="fas fa-envelope mr-3"></i>E: contact@hms.com</p>
            <p><i class="fas fa-phone mr-3"></i>T: + 353 01 23456</p>
            <p><i class="fas fa-print mr-3"></i>M: + 353 087 6543210</p>
          </div>

          <hr class="w-100 clearfix d-md-none" />
        </div>
      </section>

      <hr class="my-3">

      <section class="p-3 pt-0">
        <div class="row d-flex align-items-center">
          <div class="col-md-7 col-lg-6 text-center text-md-start">
            <div class="p-3">
              © 2022 Copyright:
              <a class="text-white" href="https://holidays-management.herokuapp.com">Holidays Management System</a>
              <p><span class="pictures-credits text-white">Homepage theme image by Walkerssk via <a href="https://pixabay.com/photos/beach-paradise-island-palm-trees-1761410/" target="_blank" rel= "noreferrer">pixabay.com</a>, 
              Calendar image by Samuel1983 via <a href="https://pixabay.com/illustrations/icon-calendar-stylized-1549619/" target="_blank" rel= "noreferrer">pixabay.com</a></span></p>
            </div>
          </div>

          <div class="col-md-5 col-lg-6 ml-lg-0 text-center text-md-end">
            <a class="btn btn-primary btn-floating m-1 btn-s-media" style="background-color: #333333; color: #fff;" href="https://github.com/JarekPo/holidays" role="button" target="_blank" rel= "noreferrer"><i class="fab fa-github">GitHub</i></a>
            <a class="btn btn-primary btn-floating m-1 btn-s-media" style="background-color: #0082ca; color: #fff;" href="https://www.linkedin.com/in/jarek-polowy/" role="button" target="_blank" rel= "noreferrer"><i class="fab fa-linkedin-in">LinkedIn</i></a>
            <a class="btn btn-primary btn-floating m-1 btn-s-media" style="background-color: #55acee; color: #fff;" href="https://twitter.com" role="button"  target="_blank" rel= "noreferrer"><i class="fab fa-twitter">Twiter</i></a>
            <a class="btn btn-primary btn-floating m-1 btn-s-media" style="background-color: #3b5998; color: #fff;" href="https://facebook.com" role="button" target="_blank" rel= "noreferrer"><i class="fab fa-facebook-f">Facebook</i></a>
            <a class="btn btn-primary btn-floating m-1 btn-s-media-google" style="background-color: white" href="https://www.google.com" role="button"  target="_blank" rel= "noreferrer">
              <i class="fab fa-google" style="font-weight: bold"></span><span style="color: #4285f4;">G</span><span style="color: #ea4335;">o</span><span style="color: #fbbc05;">o</span><span style="color: #4285f4;">g</span><span style="color: #34a853;">l</span><span style="color: #ea4335;">e</span></i>
            </a>
          </div>
        </div>
      </section>
    </div>
  </footer>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-light navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <%= image_tag("logo.png", :alt => "logo", :class => "logo-header", width: "50", height: "48") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse page-navbar" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "About", home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <% if current_user.admin == true %>
            <li class="nav-item">
              <%= link_to 'Manage Calendar', requests_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Manage Holiday Requests', events_path, class:"nav-link" %>
            </li>
          <li class="nav-item">
            <%= link_to "Edit Admin Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Manage Holiday Requests', events_path, class:"nav-link" %>
            </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if user_signed_in? %>
          <li class="nav-item text-center">
            <%= link_to "Holidays Calendar", home_calendar_path, class:"nav-link calendar-link" %>
          </li>
        <% end %>
      </ul>
      <span class="navbar-text">
        Holidays Management System <br /> Manage Easier!
      </span>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="d-flex justify-content-center"><br/>
	<h1 class="" id="header" style="position:relative">About</h1>
</div>
<div class="wrapper-about container">
	<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-in-text section-about">
		<h3>About Holidays Management System</h3>
		<p>The Holidays Management System has been developed to help employees apply for and managers manage their holidays. 
		You can apply for holidays without making an appointment with your manager; simply fill in the <%= link_to "Holiday Request Form", new_event_path %> to be processed. 
		Once approved by the manager, the annual leave with the employee's name will appear in the appropriate place on the <%= link_to "Calendar", home_calendar_path %>.
		</p>
		<hr />
	</div>
	<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 section-about">
		<h3>Terms of application for annual leave.</h3>
		<ul>
			<li>You are entitled to 20 days of holiday per year.</li>
			<li>Holiday may not be granted when:</li>
				<ul>
					<li>The request for holiday is sent too late. Please give the manager at least 2 days to review the request.</li>
					<li>You do not have enough holidays left to cover the requested period.</li>
				</ul>
			<li>During the peak season, a limited number of employees can take holidays. Each case will be considered individually.</li>
			<li>In the event of emergencies or other special circumstances, please provide the relevant information in the Notes field.</li>
			<li>If you are unable or unwilling to complete a holiday request form, please make an appointment with your manager.</li>
		</ul>
		<hr />
	</div>
	<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 section-about">
		<h3>How does it work?</h3>
		<ol>
			<li>Log in.</li>
			<li>Check the Holidays Calendar for available dates.</li>
			<li>Fill in the Holiday Requests form. Important: please provide a valid email address as we will use it to communicate with you.</li>
			<li>Wait for approval.</li>
			<li>Your holiday will appear on the calendar once granted.</li>
		</ol>
		<hr />
	</div>
	<% if user_signed_in? && current_user.admin == true %>
		<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 section-about">
			<h3>How to put holidays on the calendar?</h3>
			<ol>
				<li>Check the Holiday Requests page for new entries.</li>
				<li>Check the Holidays Calendar, it will help you decide whether to grant a holiday.</li>
				<li>If granted, place the holiday on the Holidays Calendar by completing the New Holiday form.</li>
				<li>The new holiday will appear on the Holidays Calendar.</li>
			</ol>
			<hr />
		</div>
	<% end %>
	<% if user_signed_in? && current_user.admin == false %>
		<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
			<%= link_to "Create Holiday Request", new_event_path %>
		</div>
	<% end %>
	<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-in-text section-about">
		<h3>Do you have questions? Get in touch with us:</h3><br/>
		<p>email: <a href="mailto:contact@hms.com?subject=Holiday request">contact@hms.com</a></p>
		<p>tel: <a href="tel:+353123456">01 23456</a></p>
		<p>mobile: <a href="tel:+353876543210">087 6543210</a></p>
		<hr />
	</div>
</div>
<script> 
$(document).ready(function(){
    $("#header").animate({bottom: '40px'}, 600);
  });
</script>

app/views/home/calendar.html.erb
<div class="container wrapper-calendar mb-4">
  <div id="header" class="d-flex justify-content-between mb-4" style="position:relative">
    <% if !user_signed_in? %>
      <h1>Holidays Calendar</h1>
      <p>You must be <%= link_to "logged in", new_user_session_path %> to see the entries in the Calendar.</p>
    <% else %>
      <% if current_user.admin == true %>
          <h1>Holidays Calendar</h1>
          <div>
            <%= link_to 'Add Holiday', requests_path, class:"btn btn-calendar"%>
          </div>
      <% else %>
          <h1>Holidays Calendar</h1>
          <div>
            <%= link_to 'Create Holiday Request', new_event_path, class:"btn btn-calendar"%>
          </div>
      <% end %>
    <% end %>
  </div>
  <div id="calendar"></div>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var calendarEl = document.getElementById('calendar');
      
      if (window.innerWidth >= 990 ){
        var calendar = new FullCalendar.Calendar(calendarEl, {
          headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: 'dayGridMonth,timeGridWeek,timeGridDay'
          },
          displayEventTime: false,
          navLinks: true, // can click day/week names to navigate views
          selectable: true,
          selectMirror: true,
          events: '/requests.json',
          editable: true,
          dayMaxEvents: true, // allow "more" link when too many events
        });
      }
      else{
        var calendar = new FullCalendar.Calendar(calendarEl, {
          headerToolbar: {
            left: 'prev,next',
            center: '',
            right: 'title'
          },
          displayEventTime: false,
          navLinks: true,
          selectable: true,
          selectMirror: true,
          events: '/requests.json',
          editable: true,
          dayMaxEvents: true, 
        });
      }
      calendar.render();
    });

  </script>
</div>
<script> 
  $(document).ready(function(){
    $("#header").animate({bottom: '40px'}, 600);
  });
</script>

app/views/home/index.html.erb
<div class="d-flex justify-content-center"><br/>
	<h1 class="text-center" id="header" style="display:none; position:relative">Holidays Management System</h1>
</div>
<div class="wrapper-home text-center">

	<% if user_signed_in? %>
		<% if current_user.admin == true %>
			<div class="btn btn1 btn-lg btn-secondary btn-lg-primary fw-bold" style="display:none; position: relative">
	            <%= link_to "View Holidays Calendar", home_calendar_path %>
	        </div>
	        <div class="btn btn2 btn-lg btn-secondary btn-lg-primary fw-bold" style="display:none; position: relative">
	            <%= link_to "Manage Calendar Entries", requests_path %>
	        </div>
		<% else %>
	        <div class="btn btn1 btn-lg btn-secondary btn-lg-primary fw-bold" style="display:none; position: relative">
	            <%= link_to "Create Holiday Request", new_event_path %>
	        </div>
	        <div class="btn btn2 btn-lg btn-secondary btn-lg-primary fw-bold" style="display:none; position: relative">
	            <%= link_to "View Calendar", home_calendar_path %>
	        </div>
	    <% end %>
    <% else %>
        <div class="btn btn1 btn-lg btn-secondary btn-lg-primary fw-bold" style="display:none; position: relative">
            <%= link_to 'Login', new_user_session_path, class:"nav-link" %>
        </div>
        <div class="btn btn2 btn-lg btn-secondary btn-lg-primary fw-bold" style="display:none; position: relative">
            <%= link_to 'Register', new_user_registration_path, class:"nav-link" %>
        </div>
    <% end %>
</div>
<script> 
$(document).ready(function(){
	$("#header").fadeIn(900);
    $("#header").animate({bottom: '40px'}, 600);
	$(".btn1").delay(1500).fadeIn(900);
	$(".btn1").animate({top: '90px'}, 200)
	$(".btn2").delay(1500).fadeIn(1300);
	$(".btn2").animate({top: '90px'}, 200)
  });
</script>
   

app/views/requests/edit.html.erb
<h1 class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">Edit Approved Holiday</h1>

<%= render "form", request: @request %>

<br>

<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
  <%= link_to "Show This Holiday", @request %> 
  <%= link_to "Back To Approved Holidays", requests_path %>
</div>

app/views/requests/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin == true %>
    <h1 id="header" style="position:relative" class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">Approved Holidays</h1>
    <span class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
      <%= link_to "Add Holiday To Calendar", new_request_path %>
    </span>
    <div id="requests" class="wrapper-approved">
      <% @requests.each do |request| %>
        <hr class="container" />
        <%= render request %>
        <p  class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
        <%= link_to "Show This Holiday", request %>
        </p><br/>
      <% end %>
    </div>
  <% else %>
    <h1 id="header" style="position:relative" class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">Approved Holidays</h1>
    <span class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
      <%= link_to "Back", :back %>
    </span>
    <div id="requests" class="wrapper-approved">
      <% @requests.each do |request| %>
        <hr class="container" />
        <%= render request %>
        <br/>
      <% end %>
    </div>
  <% end %>
<% end %>

<script> 
$(document).ready(function(){
    $("#header").animate({bottom: '40px'}, 600);
	$(".btn1").fadeIn(900);
	$(".btn1").animate({top: '90px'}, 200)
	$(".btn2").fadeIn(1300);
	$(".btn2").animate({top: '90px'}, 200)
  });
</script>

app/views/requests/new.html.erb
<% if user_signed_in? %>
  <% if current_user.admin == true %>
    <h1 class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4">New Holiday</h1>
    <%= render "form", request: @request %>
    <br>
    <div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
      <%= link_to "Back To Approved Holidays", requests_path %>
    </div>
  <% else %>
    <div class="container links-secondary min-vh">
      <p>Unauthorized access</p>		
      <%= link_to "Back", :back %>
		</div>
  <% end %>
<% end %>

app/views/requests/show.html.erb
<%= render @request %>

<div class="col-md-10 col-lg-8 col-xl-6 mx-auto mb-4 links-secondary">
  <%= link_to "Edit This Holiday", edit_request_path(@request) %>
  <%= link_to "Back to Approved Holidays", requests_path %>
  <%= link_to "Show Calendar", home_calendar_path %>
  <%= button_to "Delete this Holiday", @request, method: :delete, class:"btn btn-sm-primary mt-4" %>
</div>